routes/web.php
<?php

use App\Http\Controllers\Asignaciones\AsignacionesController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UtilitariosController;
use App\Models\Usuario;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'auth' ], function() {
    Route::get('/', function () { return redirect(getHomeRouteForUser()); });

    /* ========================== ASIGNACIONES ==========================*/
    Route::view('/asignaciones/conglomerado',     'pages/asignaciones/AsigConglomeradoRuta')->name('asignaciones/conglomerado')->middleware('role:COORDINADOR,MASTER');
    Route::post('/getAsigConglomeradoRuta',       [AsignacionesController::class, 'ListarReportesAsignacion'])->name('getAsigConglomeradoRuta');
    Route::post('/SaveAsigConglomeradoRuta',      [AsignacionesController::class, 'GuardarAsigConglomeradoRuta'])->name('SaveAsigConglomeradoRuta');
    Route::post('/deleteAsigCongloRuta',          [AsignacionesController::class, 'EliminarAsignacionCongloRuta'])->name('deleteAsigCongloRuta');

    

    Route::view('/asignaciones/ruta', 'pages/asignaciones/AsigRutaNombre', [
        'data' => json_encode(Usuario::all())        
    ])->name('asignaciones/ruta')->middleware('role:ENCUESTADOR,MASTER'); 

    Route::post('/getAsigRutaNombre',       [AsignacionesController::class, 'ListarReportesAsignacion'])->name('getAsigRutaNombre');
    Route::post('/SaveAsigRutaNombre',      [AsignacionesController::class, 'GuardarAsigRutaNombre'])->name('SaveAsigRutaNombre');

    
    /* ========================== SEGMENTOS ==========================*/
    Route::view('/segmentos/segmento', 'pages/segmentos/ActualizaSegmentos', [
        'data' => json_encode(Usuario::all())        
    ])->name('segmentos/segmento')->middleware('role:MONITOR,MASTER'); 

    Route::post('/getActualizaSegmentos',       [AsignacionesController::class, 'ListarReportesSegmentos'])->name('getActualizaSegmentos');
    Route::post('/SaveActualizaSegmentos',      [AsignacionesController::class, 'GuardarActSegmentos'])->name('SaveActualizaSegmentos');
    Route::post('/deleteAsignacionSegmento',    [AsignacionesController::class, 'EliminarAsignacionSegmentos'])->name('deleteAsignacionSegmento');


    /* ========================== REPORTES ==========================*/
    Route::view('/reportes/asignaciones',   'pages/reportes/Asignaciones')->name('reportes/asignaciones')->middleware('role:MASTER');
    Route::view('/reportes/revertidos',     'pages/reportes/Revertidos')->name('reportes/revertidos')->middleware('role:MASTER');
    Route::post('/getSegmentosRevertidos',      [AsignacionesController::class, 'ListarReportesRevertidos'])->name('getSegmentosRevertidos');
    Route::view('/reportes/marco',     'pages/reportes/MarcoEncuesta')->name('reportes/marco')->middleware('role:MASTER');
    Route::post('/getMarcoEncuesta',      [AsignacionesController::class, 'ListarReportesMarcoEncuesta'])->name('getMarcoEncuesta');


    /* ========================== CARGAR EXCEL ==========================*/
    Route::view('/procesar/marco',   'pages/procesar/CargarMarco')->name('procesar/marco')->middleware('role:MASTER');
    Route::post('/procesar',         [AsignacionesController::class, 'ImportarExcelMarco'])->middleware('role:MASTER');

    /* ========================== FILTROS ==========================*/
    Route::get('/getAnios',             [UtilitariosController::class, 'listarAnios'])->name('getAnios');
    Route::post('/getMeses',            [UtilitariosController::class, 'listarMeses'])->name('getMeses');
    Route::post('/getSedeOpe',          [UtilitariosController::class, 'listarSedesOperativas'])->name('getSedeOpe');   
    Route::post('/getPeriodo',          [UtilitariosController::class, 'listarPeriodos'])->name('getPeriodo');
    Route::post('/getConglomerado',     [UtilitariosController::class, 'listarConglomerados'])->name('getConglomerado');
    Route::post('/getEquipos',          [UtilitariosController::class, 'listarEquipos'])->name('getEquipos');
    Route::post('/getRutas',            [UtilitariosController::class, 'listarRutas'])->name('getRutas');
    Route::post('/getUsuarios',         [UtilitariosController::class, 'listarUsuarios'])->name('getUsuarios');
});

/* ========================== AUTENTICACIÓN ==========================*/

Route::view('default',  'auth/login')->name('default')->middleware('guest');
Route::post('/login',   [AuthController::class, 'irIngreso']);
Route::get('/salir',    [AuthController::class, 'irCerrarSesion'])->name('salir');
Route::view('restriccion',  'restriccion')->name('restriccion');

function getHomeRouteForUser()
{
    if (Auth::check()) {
        if (Auth::user()->hasRole('ENCUESTADOR')) {
            return route('asignaciones/ruta');
        } elseif (Auth::user()->hasRole('MONITOR')) {
            return route('segmentos/segmento');
        }
    }

    return route('asignaciones/conglomerado'); 
}

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Usuario extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    
    protected $table = 'T_USUARIO';
    protected $primaryKey = 'ID';
    public $incrementing= true;   
    protected $fillable = ['ID','USUARIO', 'CLAVE', 'CARGO_ID', 'TELEFONO', 'EMAIL', 'ESTADO', 'NOMBRES', 
         'APELLIDOS', 'CORREO', 'DNI', 'COD_SEDE_OPERATIVA', 'EQUIPO', 'RUTA', 'HASHPASSWORD','REMEMBER_TOKEN'
    ]; 

    protected $username = 'USUARIO';
    protected $password = 'HASHPASSWORD';
    public $timestamps = false;
    protected $hidden = [
        'CLAVE', 'REMEMBER_TOKEN',
    ];

    public function hasRole(...$roles)
    {
        $cargoId = $this->attributes['CARGO_ID'];
        $userRole = 'MASTER';
        switch ($cargoId) {
            case 4:
                $userRole = 'COORDINADOR';
                break;
            case 18:
                $userRole = 'ENCUESTADOR';
                break;
            case 19:
                $userRole = 'MONITOR';
                break;
        }
        return in_array($userRole, $roles);
    }

    
    public function getCargonameAttribute()
    {
        $cargoId = $this->attributes['CARGO_ID'];
        switch ($cargoId) {
            case 4:
                return 'COORDINADOR DEPARTAMENTAL';
            case 18:
                return 'ENCUESTADOR';
            case 19:
                return 'MONITOR DE CAMPO';
            default:
                return 'MASTER';
        }
    }
  
    public function getOnlyCargo()
    {
        $cargoId = $this->attributes['CARGO_ID'];
        switch ($cargoId) {
            case 4:
                return 'COORDINADOR';
            case 18:
                return 'ENCUESTADOR';
            case 19:
                return 'MONITOR';
            default:
                return 'MASTER';
        }
    }

    public function getCargoRutaURL()
    {
        $cargoId = $this->attributes['CARGO_ID'];
        switch ($cargoId) {
            case 4:
                return 'asignaciones/conglomerado';
            case 18:
                return 'asignaciones/ruta';
            case 19:
                return 'segmentos/segmento';
            default:
                return 'asignaciones/conglomerado';
        }
    }
   
}

resources/views/master/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © INEI.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    DNCE INFORMÁTICA
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/master/header.blade.php
<header id="page-topbar" class="isvertical-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box text-center">
                <a href="#" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{{asset('assets/images/logo-inei.png')}}" alt="" height="26">
                    </span>
                    <span class="logo-lg">
                        <img src="{{asset('assets/images/logo-inei.png')}}" alt="" height="65">
                    </span>
                </a>
                {{-- <a href="index.html" class="logo logo-light">
                    <span class="logo-lg">
                        <img src="{{asset('assets/images/logo_inei.png')}}" alt="" height="30">
                    </span>
                    <span class="logo-sm">
                        <img src="{{asset('assets/images/logo-light-sm.png')}}" alt="" height="26">
                    </span>
                </a> --}}
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect vertical-menu-btn">
                <i class="bx bx-menu align-middle"></i>
            </button>
        </div>
        <div class="d-flex">
            <!-- start page title -->
            <div class="page-title-box align-self-center d-none d-md-block text-center">
                <h6 class="page-title fw-semibold display-4 mb-0">SISTEMA DE ASIGNACIÓN DE RUTAS Y ACTUALIZACIÓN DE SEGMENTACIÓN 2023</h6>
            </div>
            <!-- end page title -->

        </div>

        <div class="d-flex">

            {{-- <div class="dropdown d-inline-block language-switch ms-2">
                <button type="button" class="btn header-item" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="header-lang-img" src="assets/images/us.jpg" alt="Header Language" height="18">
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="sp">
                        <img src="assets/images/spain.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">Spanish</span>
                    </a>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-search icon-sm align-middle"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0">
                    <form class="p-2">
                        <div class="search-box">
                            <div class="position-relative">
                                <input type="text" class="form-control rounded bg-light border-0" placeholder="Search...">
                                <i class="bx bx-search search-icon"></i>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon" id="page-header-notifications-dropdown-v"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell icon-sm align-middle"></i>
                    <span class="noti-dot bg-danger rounded-pill">4</span>
                </button>
                <div class="dropdown-menu dropdown-menu-xl dropdown-menu-end p-0"
                    aria-labelledby="page-header-notifications-dropdown-v">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h5 class="m-0 font-size-15"> Notifications </h5>
                            </div>
                            <div class="col-auto">
                                <a href="#!" class="small fw-semibold text-decoration-underline"> Mark all as read</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 250px;">
                        <a href="#!" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <img src="assets/images/avatar-3.jpg" class="rounded-circle avatar-sm" alt="user-pic">
                                </div>
                                <div class="flex-grow-1">
                                    <p class="text-muted font-size-13 mb-0 float-end">1 hour ago</p>
                                    <h6 class="mb-1">James Lemire</h6>
                                    <div>
                                        <p class="mb-0">It will seem like simplified English.</p>
                                    </div>
                                </div>
                    
                            </div>
                        </a>
                        <a href="#!" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="flex-shrink-0 avatar-sm me-3">
                                    <span class="avatar-title bg-primary rounded-circle font-size-18">
                                        <i class="bx bx-cart"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <p class="text-muted font-size-13 mb-0 float-end">3 min ago</p>
                                    <h6 class="mb-1">Your order is placed</h6>
                                    <div>
                                        <p class="mb-0">If several languages coalesce the grammar</p>
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 btn-block text-center" href="javascript:void(0)">
                            <i class="uil-arrow-circle-right me-1"></i> <span>View More..</span>
                        </a>
                    </div>
                </div>
            </div> --}}

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item user text-start d-flex align-items-center"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{{asset('assets/images/anonimo.png')}}" alt="Avatar">
                    <span class="d-none d-xl-inline-block ms-2 fw-medium font-size-15">
                        @if(Auth::check())
                            {{Auth::user()->USUARIO}}
                        @else 
                            INEI
                        @endif
                    </span>
                </button>
                @if(Auth::check())
                    <div class="dropdown-menu dropdown-menu-end pt-0">
                        <div class="p-3 border-bottom text-center">
                            <h6 class="mb-0">{{Auth::user()->cargoname }}</h6>
                            <p class="mb-0 font-size-11 "> {{Auth::user()->NOMBRES }}</p>
                        </div>
                        {{-- <div class="dropdown-divider"></div> --}}
                        <a class="dropdown-item" href="{{route('salir')}}">
                            <i class="mdi mdi-logout text-muted font-size-16 align-middle me-2"></i> 
                            <span class="align-middle">Cerrar Sesión</span>
                        </a>
                    </div>
                @endif
            </div>
        </div>
    </div>
</header>

resources/views/master/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta content="text/html; charset="utf-8" http-equiv="content-type"/>
        {{-- <title>INEI | Sistema de Asignación de Rutas</title> --}}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="keywords" name="PERÚ,  INEI ,  Perú, economy , INFORMATICA, INSTITUTO, ECONOMIA, Statistical Instituto Nacional de Estadística e Informática,estadisticas, National Institute of Statistics, Censos, EncuestasIndicadores, PBI, pbi, IPC, ipc, Índice de Precios, indice de Precios, price tax" />
        <meta content="description" name="INEI PERÚ El Instituto Nacional de Estadística e Informática (INEI) es el Órgano Rector de los Sistemas Nacionales de Estadística e Informática en el Perú." />        

        @yield('esTitulo')
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <link href="{{asset('assets/images/favicon.ico')}}" rel="shortcut icon">
        <link href="{{asset('assets/DataTables-1.10.15/media/css/jquery.dataTables.css?v=1.0') }}" rel="stylesheet" type="text/css">
        <link href="{{asset('assets/css/bootstrap.min.css?v=1.0')}}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/css/icons.min.css?v=1.0')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/css/app.min.css?v=1.0')}}" id="app-style" rel="stylesheet" type="text/css" />
        @yield('esStyles') 
        <script type="text/javascript">
            window.APP_URL = '{{ asset("/") }}';
            window.APP_IMG = APP_URL+'assets/images/';      
        </script>
    </head>    
    <body>
        <div id="layout-wrapper">
            @include('master.header')
           
            @include('master.menu')  

            <div class="main-content">
                <div class="page-content">
                    <div class="container-fluid">
                        
                        <div id="appAsignacionSIS">
                            @yield('esBodyPrincipal') 
                        </div>                      

                    </div>
                </div>
                @include('master.footer')  
            </div>
        </div>       

        <!-- JAVASCRIPT -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js?v=1.0"></script>
        <script src="{{asset('assets/DataTables-1.10.15/media/js/jquery.dataTables.min.js?v=1.0') }}"></script> 
        <script src="{{asset('assets/js/bootstrap.bundle.min.js?v=1.0')}}"></script>
        <script src="{{asset('assets/js/metismenujs.min.js?v=1.0')}}"></script>
        <script src="{{asset('assets/js/simplebar.min.js?v=1.0')}}"></script>
        <script src="{{asset('assets/js/eva.min.js?v=1.0')}}"></script> 
        <script src="{{asset('assets/js/app.js?v=1.0')}}"></script>
        
        @vite('resources/js/app.js')
        <script type="text/javascript">            
            $(document).ready(function () {
                $("#IdInicio").removeClass("mm-active");
                $("#IdInicioURL").removeClass("active");
            });
        </script>
        @yield('esScript')
    </body>

</html>

resources/views/master/menu.blade.php
<div class="vertical-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box text-center">
        <a href="#" class="logo logo-dark">
            <span class="logo-sm">
                <img src="{{asset('assets/images/logo-inei.png')}}" alt="" height="26">
            </span>
            <span class="logo-lg">
                <img src="{{asset('assets/images/logo-inei.png')}}" alt="" height="65">
            </span>
        </a>        
        {{-- <a href="index.html" class="logo logo-light">
            <span class="logo-lg">
                <img src="{{asset('assets/images/logo-light.png')}}" alt="" height="30">
            </span>
            <span class="logo-sm">
                <img src="{{asset('assets/images/logo-light-sm.png')}}" alt="" height="26">
            </span>
        </a> --}}
    </div>

    <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect vertical-menu-btn">
        <i class="bx bx-menu align-middle"></i>
    </button>

    <div data-simplebar class="sidebar-menu-scroll">
        <div id="sidebar-menu">
            <ul class="metismenu list-unstyled mt-4" id="side-menu">

                <li class="menu-title" data-key="t-layouts">Principal</li>                
                <li id="IdInicio">
                    <a href="{{ route(Auth::user()->getCargoRutaURL())}}" id="IdInicioURL">
                        <i class="bx bx-home-alt icon nav-icon"></i>
                        <span class="menu-item" data-key="t-horizontal">Inicio</span>
                    </a>
                </li>

                <li class="menu-title" data-key="t-menu">Asignaciones</li>
                <li id="IdAsignaciones">
                    <a href="javascript: void(0);" class="has-arrow">
                        <i class="bx bx-pie-chart-alt-2 icon nav-icon"></i>
                        <span class="menu-item" >Asignación de Carga</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{{route('asignaciones/conglomerado')}}">Asignación de <br>Conglomerado a<br> Ruta</a></li>
                        <li><a href="{{route('asignaciones/ruta')}}">Asignación de <br>Ruta a Nombre</a></li>
                    </ul>
                </li>
                <li class="menu-title" data-key="t-menu">Segmentos</li>
                <li id="IdSegmentos">
                    <a href="{{route('segmentos/segmento')}}">
                        <i class="bx bx-cube icon nav-icon"></i>
                        <span class="menu-item">Actualizar Segmento</span>
                    </a>
                </li>
                <li class="menu-title" data-key="t-menu">Reportes Generales</li>
                <li id="IdReportes">
                    <a href="javascript: void(0);" class="has-arrow">
                        <i class="bx bx-file icon nav-icon"></i>
                        <span class="menu-item" >Reportes</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{{route('reportes/asignaciones')}}" >Reporte de <br>Asignaciones</a></li>
                        <li><a href="{{route('reportes/revertidos')}}">Reporte de <br>Asignaciones <br>Revertidas</a></li>
                        <li><a href="{{route('reportes/marco')}}">Reporte de <br>Marco <br>Encuesta</a></li>
                    </ul>
                </li>
                <li class="menu-title" data-key="t-menu">Procesar Excel</li>
                <li id="IdSegmentos">
                    <a href="{{route('procesar/marco')}}">
                        <i class="bx bx-cloud-upload icon nav-icon"></i>
                        <span class="menu-item">Cargar Marco</span>
                    </a>
                </li>
                <li class="menu-title" data-key="t-pages">Cerrar Sesión</li>

                <li>
                    <a href="{{route('salir')}}">
                        <i class="bx bx-log-in icon nav-icon"></i>
                        <span class="menu-item" data-key="t-authentication">Salir</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>